# Generated by Django 4.1.6 on 2023-02-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
